name = "qube-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/1 * * * *"]

[[kv_namespaces]]
binding = "QUBE_KV"
id = "96edcd46f8ed471693b63783e4de9936"

[vars]
ADBC_API_URL = "https://api.adbc.io/api/v3/reward/campaigns"
ADBC_TOKEN = "10bc38e2dea97e717f70aacb6228f473"
